function J_sym = fun_J_nf3nz4_ord3(in1)
%fun_J_nf3nz4_ord3
%    J_sym = fun_J_nf3nz4_ord3(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    08-Aug-2024 12:00:29

J1 = in1(:,1);
J2 = in1(:,2);
J3 = in1(:,3);
J4 = in1(:,4);
J5 = in1(:,5);
J6 = in1(:,6);
J7 = in1(:,7);
J_sym = [J1,J2,J3,J4,J5,J6,J7];
end
