function H_sym = fun_H_nf3nz4_ord3(in1)
%fun_H_nf3nz4_ord3
%    H_sym = fun_H_nf3nz4_ord3(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    23-Mar-2026 09:14:23

H1_1 = in1(:,8);
H2_1 = in1(:,9);
H2_2 = in1(:,10);
H3_1 = in1(:,11);
H3_2 = in1(:,12);
H3_3 = in1(:,13);
H4_1 = in1(:,14);
H4_2 = in1(:,15);
H4_3 = in1(:,16);
H4_4 = in1(:,17);
H5_1 = in1(:,18);
H5_2 = in1(:,19);
H5_3 = in1(:,20);
H5_4 = in1(:,21);
H5_5 = in1(:,22);
H6_1 = in1(:,23);
H6_2 = in1(:,24);
H6_3 = in1(:,25);
H6_4 = in1(:,26);
H6_5 = in1(:,27);
H6_6 = in1(:,28);
H7_1 = in1(:,29);
H7_2 = in1(:,30);
H7_3 = in1(:,31);
H7_4 = in1(:,32);
H7_5 = in1(:,33);
H7_6 = in1(:,34);
H7_7 = in1(:,35);
H_sym = reshape([H1_1,H2_1,H3_1,H4_1,H5_1,H6_1,H7_1,H2_1,H2_2,H3_2,H4_2,H5_2,H6_2,H7_2,H3_1,H3_2,H3_3,H4_3,H5_3,H6_3,H7_3,H4_1,H4_2,H4_3,H4_4,H5_4,H6_4,H7_4,H5_1,H5_2,H5_3,H5_4,H5_5,H6_5,H7_5,H6_1,H6_2,H6_3,H6_4,H6_5,H6_6,H7_6,H7_1,H7_2,H7_3,H7_4,H7_5,H7_6,H7_7],[7,7]);
end
